version: '3'
services:
  php:
    container_name: docker-lamp-php
    build: ./docker/php-apache
    ports:
      - 80:80
    volumes:
      - ./dist:/var/www/html

  mysql:
    container_name: docker-lamp-mysql
    platform: linux/x86_64
    image: mysql:latest
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: localdb
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    container_name: docker-lamp-phpmyadmin
    platform: 'linux/amd64'
    image: phpmyadmin:latest
    depends_on:
      - mysql
    ports:
      - 8888:80
    volumes:
      - phpmyadmin:/sessions
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  phpmyadmin:
    driver: local
  mysql:
    driver: local
